services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: true

    VideoGamesRecords\DwhBundle\Controller\Player\GetMedalsByTime:
        arguments:
            - '@vgr.dwh.repository.player'
        calls:
            - [ setContainer, [ "@service_container" ] ]

    VideoGamesRecords\DwhBundle\Controller\Player\GetPositions:
        arguments:
            - '@vgr.dwh.repository.player'
        calls:
            - [ setContainer, [ "@service_container" ] ]
