services:
    vgr.dwh.data_provider.core:
        class: VideoGamesRecords\DwhBundle\DataProvider\CoreProvider
        calls:
            - [ 'addStrategy', [ '@vgr.dwh.data_provider.strategy.core.game' ] ]
            - [ 'addStrategy', [ '@vgr.dwh.data_provider.strategy.core.player' ] ]
            - [ 'addStrategy', [ '@vgr.dwh.data_provider.strategy.core.team' ] ]

    vgr.dwh.data_provider.strategy.core.game:
        class: VideoGamesRecords\DwhBundle\DataProvider\Strategy\Core\CoreGameStrategy
        arguments:
            - '@doctrine.orm.entity_manager'

    vgr.dwh.data_provider.strategy.core.player:
        class: VideoGamesRecords\DwhBundle\DataProvider\Strategy\Core\CorePlayerStrategy
        arguments:
            - '@doctrine.orm.entity_manager'

    vgr.dwh.data_provider.strategy.core.team:
        class: VideoGamesRecords\DwhBundle\DataProvider\Strategy\Core\CoreTeamStrategy
        arguments:
            - '@doctrine.orm.entity_manager'

    vgr.dwh.data_provider.top:
        class: VideoGamesRecords\DwhBundle\DataProvider\TopProvider
        calls:
            - [ 'addStrategy', [ '@vgr.dwh.data_provider.strategy.top.game' ] ]
            - [ 'addStrategy', [ '@vgr.dwh.data_provider.strategy.top.player' ] ]

    vgr.dwh.data_provider.strategy.top.game:
        class: VideoGamesRecords\DwhBundle\DataProvider\Strategy\Top\TopGameStrategy
        arguments:
            - '@doctrine.orm.dwh_entity_manager'
            - '@doctrine.orm.entity_manager'

    vgr.dwh.data_provider.strategy.top.player:
        class: VideoGamesRecords\DwhBundle\DataProvider\Strategy\Top\TopPlayerStrategy
        arguments:
            - '@doctrine.orm.dwh_entity_manager'
            - '@doctrine.orm.entity_manager'



