services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    VideoGamesRecords\DwhBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
    VideoGamesRecords\DwhBundle\Service\Player:
        class:    VideoGamesRecords\DwhBundle\Service\Player
        arguments: [
            "@=service('doctrine.orm.dwh_entity_manager')",
            "@=service('doctrine.orm.default_entity_manager')"
            ]
    VideoGamesRecords\DwhBundle\Service\Game:
        class:    VideoGamesRecords\DwhBundle\Service\Game
        arguments: [
            "@=service('doctrine.orm.dwh_entity_manager')",
            "@=service('doctrine.orm.default_entity_manager')"
            ]
    VideoGamesRecords\DwhBundle\Service\Team:
        class:    VideoGamesRecords\DwhBundle\Service\Team
        arguments: [
            "@=service('doctrine.orm.dwh_entity_manager')",
            "@=service('doctrine.orm.default_entity_manager')"
            ]
    VideoGamesRecords\DwhBundle\Service\Article:
        class:    VideoGamesRecords\DwhBundle\Service\Article
        arguments: [
            "@=service('doctrine.orm.dwh_entity_manager')",
            "@=service('doctrine.orm.default_entity_manager')"
            ]