services:
    _defaults:
        autowire: true
    dwh.player:
        class:    VideoGamesRecords\DwhBundle\Service\Player
        arguments: ["@=service('doctrine.orm.entity_manager').getRepository('VideoGamesRecordsDwhBundle:Player')"]
    dwh.game:
        class:    VideoGamesRecords\DwhBundle\Service\Game
        arguments: ["@=service('doctrine.orm.entity_manager').getRepository('VideoGamesRecordsDwhBundle:Game')"]