services:
    _defaults:
        autowire: true
    dwh.player:
        class:    VideoGamesRecords\DwhBundle\Service\Player
        arguments: [
            "@=service('doctrine.orm.dwh_entity_manager')",
            "@=service('doctrine.orm.default_entity_manager')"
            ]
    dwh.game:
        class:    VideoGamesRecords\DwhBundle\Service\Game
        arguments: [
            "@=service('doctrine.orm.dwh_entity_manager')",
            "@=service('doctrine.orm.default_entity_manager')"
            ]