services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    VideoGamesRecords\DwhBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Migrations,Service,Tests,Kernel.php}'
    VideoGamesRecords\DwhBundle\Service\PlayerService:
        public: true
        class:    VideoGamesRecords\DwhBundle\Service\PlayerService
        arguments: [
            "@=service('doctrine.orm.dwh_entity_manager')",
            "@=service('doctrine.orm.default_entity_manager')"
            ]
    VideoGamesRecords\DwhBundle\Service\GameService:
        public: true
        class:    VideoGamesRecords\DwhBundle\Service\GameService
        arguments: [
            "@=service('doctrine.orm.dwh_entity_manager')",
            "@=service('doctrine.orm.default_entity_manager')"
            ]
    VideoGamesRecords\DwhBundle\Service\TeamService:
        public: true
        class:    VideoGamesRecords\DwhBundle\Service\TeamService
        arguments: [
            "@=service('doctrine.orm.dwh_entity_manager')",
            "@=service('doctrine.orm.default_entity_manager')"
            ]
    VideoGamesRecords\DwhBundle\Service\ArticleService:
        public: true
        class:    VideoGamesRecords\DwhBundle\Service\ArticleService
        arguments: [
            "@=service('doctrine.orm.dwh_entity_manager')",
            "@=service('doctrine.orm.default_entity_manager')"
            ]